### ISSUE TITLE
Font not scaling

### ISSUE THREAD

**Issue by MikeGuest** [fufar/simple-clock-card#15]
Font does not scale with background, leading to text over-shooting the tile

![snip](https://user-images.githubusercontent.com/12844043/119058915-2f696980-b9c7-11eb-980d-36d4c51f183d.PNG)

**Comment by fufar** [comment]
you tryed change font_size and padding_size options?

**Comment by DutchJaFO** [comment]
I had that problem when using the card as part of a grid card (3 columns, 2 rows).
Solution was using a vertical stack instead of trying to place it in the same grid.
It isn't pretty, but it does work.
![image](https://user-images.githubusercontent.com/39138434/120117795-347ca480-c18f-11eb-98f5-8b2b98143253.png)

Ideally the text on the card should fit the available space without having to specifiy font size every time the card is used.
